### PR TITLE
:bug: detect toJSON(github.event) in Dangerous-Workflow check

### LINKED ISSUE #3554: BUG: Dangerous-Workflow doesn't trigger on `toJSON(github.event)`
**Describe the bug**
The Dangerous-Workflow check currently only triggers when attacker-controlled data is explicitly declared in the workflow.

https://github.com/ossf/scorecard/blob/130a31f/checks/raw/dangerous_workflow.go#L31-L57

However, if the `github.event` object is converted to a JSON object (i.e. for logging) in a `run:` command on a workflow triggered by an external contribution, its contents will contain attacker-controlled data (i.e. the issue/PR title) which can be used for code injection in the workflow.

For example:

```yml
on:
  pull_request_target:

jobs:
  get-pwned:
    runs-on: ubuntu-latest
    steps:
      - name: Log event and get pwned
        run: echo '${{ toJSON(github.event) }}' | jq
```

**Expected behavior**
Dangerous-Workflow should detect this as a dangerous pattern.

### PR DESCRIPTION
**Pull request by heathdutton**
#### What kind of change does this PR introduce?

Bug fix

- [x] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?

The Dangerous-Workflow check does not detect script injection vulnerabilities when `toJSON(github.event)` or `toJSON(github)` is used in workflow run steps. These serialize the entire event/context object which contains attacker-controlled data.

#### What is the new behavior (if this is a feature change)?

The check now detects `toJSON(github.event)` and `toJSON(github)` patterns as dangerous, including case variations and whitespace.

- [x] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes

Fixes #3554

#### Special notes for your reviewer

The regex `(?i)tojson\s*\(\s*github(\s*\)|\.event)` matches:
- `toJSON(github)` - serializes entire context including event
- `toJSON(github.event)` and `toJSON(github.event.*)` - serializes event data
- Case insensitive and handles whitespace

It correctly ignores safe patterns like `toJSON(github.repository)`.

#### Does this PR introduce a user-facing change?

```release-note
Dangerous-Workflow check now detects toJSON(github.event) and toJSON(github) as dangerous patterns
```

### CODE REVIEW

File: checks/raw/dangerous_workflow.go [hunk 1]
```diff
@@ -56,6 +56,13 @@ func containsUntrustedContextPattern(variable string) bool {
 	if strings.Contains(variable, "github.head_ref") {
 		return true
 	}
+	// Check for toJSON() serializing github context or event objects.
+	// These contain untrusted data and are dangerous in shell contexts.
+	// See https://github.com/ossf/scorecard/issues/3554
+	dangerousToJSONPattern := regexp.MustCompile(`(?i)tojson\s*\(\s*github(\s*\)|\.event)`)
```
Comment (spencerschrock) [inline checks/raw/dangerous_workflow.go]: I think there's a small issue or two with this regex:
Your event alternate doesnt have the closing right parens, so it would have matched `github.events` or similar.

What do you think about:
`(?i)tojson\s*\(\s*github(?:\s*\)|\s*\.event\s*\))`

I made the alternate group non capturing, allowed some spaces before and after event, and look for a closing right paren

File: checks/raw/dangerous_workflow_test.go [hunk 2]
```diff
@@ -105,6 +105,36 @@ func TestUntrustedContextVariables(t *testing.T) {
...
+		},
+		{
+			name:     "toJSON github context",
+			variable: "toJSON(github)",
+			expected: true,
+		},
+		{
+			name:     "toJSON github.event nested",
+			variable: "toJSON(github.event.pull_request)",
+			expected: true,
```
Comment (spencerschrock) [inline checks/raw/dangerous_workflow_test.go]: Hmm, perhaps this is why you didnt close the right paren on event?

There are a lot of tricky cases here. For example:
`toJSON(github.event.pull_request.state)` would not be vulnerable, but detected by your original regex.

**Review by spencerschrock — APPROVED** [review]
I think if we just focus on `toJSON(github)` and `to.JSON(github.event)` (and not any other subfields) we avoid false positives for now, while we think of how to get the specificity right.

File: checks/raw/dangerous_workflow.go (hunk 1 above)
Comment (heathdutton) [reply checks/raw/dangerous_workflow.go]: Agreed
