### PR TITLE
:seedling: Fix pinsDependencies outcomes

### LINKED ISSUE #3855: Revisit outcomes in Pinned Dependencies probes
https://github.com/ossf/scorecard/pull/3829 needs a follow-up to get the outcomes and the evaluation scores/errors precise as mentioned by @spencerschrock here: https://github.com/ossf/scorecard/pull/3829#discussion_r1472000487.

- [ ] https://github.com/ossf/scorecard/pull/3829#discussion_r1472000487
- [ ] https://github.com/ossf/scorecard/pull/3829#discussion_r1496616001
- [ ] https://github.com/ossf/scorecard/pull/3829#discussion_r1496604686

### PR DESCRIPTION
**Pull request by spencerschrock**
#### What kind of change does this PR introduce?

probe cleanup

- [X] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?
* OutcomeNotAvailable was used for cases where there are no dependencies. 
  * The description mentions this is for API issues which isn't the case here.
* OutcomeNotApplicable was used for cases where our data is inconsistent?
* Probe outcome descriptions are wrong

#### What is the new behavior (if this is a feature change)?**
* Inconsistent data states are now `OutcomeNotSupported`, as `OutcomeError` is already used for processing errors (#3515)
  * I'm not sure this is a perfect match, open to suggestions
* Situations with no supported dependencies now use `OutcomeNotApplicable`
* Probe documentation updated to fix copy/paste mistake
* Tests were added for processing errors and no dependencies
* Finding locations were simplified (see 6439b056c306bed2429acf5304fa21338f8dfd52 for details)

- [X] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes
Fixes #3855

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note
NONE
```

### CODE REVIEW

File: probes/pinsDependencies/impl.go [hunk 1]
```diff
@@ -71,46 +72,23 @@ func Run(raw *checker.RawResults) ([]finding.Finding, string, error) {
 				e := sce.WithMessage(sce.ErrScorecardInternal, "empty File field")
 				return findings, Probe, e
 			}
-			f = f.WithMessage(*rr.Msg).WithOutcome(finding.OutcomeNotApplicable)
+			f = f.WithMessage(*rr.Msg).WithOutcome(finding.OutcomeNotSupported)
 			findings = append(findings, *f)
 			continue
 		}
 		if rr.Msg != nil {
```
Comment (raghavkaul) [inline probes/pinsDependencies/impl.go:79]: If `rr.Msg` being non-nil is some kind of exceptional state, I think its name should reflect this.

**Review by raghavkaul — APPROVED** [review]

File: probes/pinsDependencies/impl.go (hunk 1 above)
Comment (spencerschrock) [reply probes/pinsDependencies/impl.go:79]: `rr.Msg` is old (~2y) code and has the comment "// Only for debug messages". 

This was before `ProcessingErrors []ElementError` was a thing, so we could migrate away from the debug messages. That would be a separate PR in my opinion.
