### PR TITLE
Fix - Made the results.json wellformed from cron

### LINKED ISSUE #269: BUG - cron job latest.json is not wellformed
**Describe the bug**
The `cron` job produces https://storage.googleapis.com/ossf-scorecards/latest.json which is not wellformed `json`

**Expected behavior**
The json should be wellformed.

### PR DESCRIPTION
**Pull request by naveensrinivasan**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bugfix

* **What is the current behavior?** (You can also link to an open issue here)
fix #269

* **What is the new behavior (if this is a feature change)?**

  Fixed the results.json to be wellformed from the cron job.

 Changed the docker image from gsutil to cloudsdk:slim to `sed` binary which is being used with the cron.sh

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
 Yes, the latest.json will be wellformed.

* **Other information**:

### CODE REVIEW

File: cron/cron.sh [hunk 1]
```diff
@@ -17,7 +17,7 @@ SOURCE="${BASH_SOURCE[0]}"
 input=$(dirname "$SOURCE")/projects.txt
 output=$(date +"%m-%d-%Y").json
 touch "$output"
-curl https://raw.githubusercontent.com/ossf/scorecard/main/cron/projects.txt >projects.txt
+echo "{ \"results\": [" >> "$output"
```
Comment (inferno-chromium) [inline cron/cron.sh:20]: probably want to bring back the curl line ?

File: Dockerfile.gsutil [hunk 2]
```diff
@@ -26,7 +26,7 @@ ARG TARGETOS
 ARG TARGETARCH
 RUN CGO_ENABLED=0 go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o /out/scorecard .
 
-FROM gcr.io/cloud-builders/gsutil
+FROM gcr.io/google.com/cloudsdktool/cloud-sdk:slim #using cloud-sdk docker image for `sed` utility
```
Comment (inferno-chromium) [inline Dockerfile.gsutil:29]: that comment is not needed.

**Review by inferno-chromium — APPROVED** [review]

File: cron/cron.sh (hunk 1 above)
Comment (naveensrinivasan) [reply cron/cron.sh:20]: I realized the `main` branch will always have the `projects.txt` and it was redundant.

File: Dockerfile.gsutil (hunk 2 above)
Comment (naveensrinivasan) [reply Dockerfile.gsutil:29]: Ok. Thanks

File: cron/cron.sh (hunk 1 above)
Comment (inferno-chromium) [reply cron/cron.sh:20]: latest version right?, makes sense

Comment (naveensrinivasan) [reply cron/cron.sh:20]: The cloudbuild runs on merge to main.

 The cron uses the latest image from the cloudbuild.  So it will have the latest projects.txt. So the latest project.txt will be the same in the repo and also be the same inside the container.
