### PR TITLE
:sparkles:  Feature: Improve Dependabot detection through PRs

### LINKED ISSUE #874: BUG Dependency update bot not detected
**Describe the bug**
When running Scorecard against this repo https://github.com/tngan/samlify I get an score 0 on the Dependency Update Tool check, however the repo does have dependabot.

**Reproduction steps**
1. Run `docker run -e GITHUB_AUTH_TOKEN=<token> gcr.io/openssf/scorecard:stable --show-details --repo=https://github.com/tngan/samlify` 
2. Check the score of the Dependency Update Tool.

**Expected behavior**
Dependency Update Check has a non-zero score because the repo has dependabot.

### PR DESCRIPTION
**Pull request by qequ**
#### What kind of change does this PR introduce?
Feature: Update Dependency Update Tool check to search for commits made by Dependabot as Author which are in the default branch.

- [x] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?
Current Dependency Update Tool Check walks through .github directory searching for a Dependabot file.
#### What is the new behavior (if this is a feature change)?**
After searching through .github directory if it hasn't find any dependabot file it will search for commits made by Dependabot.
- [x] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes
Fixes #874 

#### Special notes for your reviewer
@azeemshaikh38 @laurentsimon this is the same feature as https://github.com/ossf/scorecard/pull/2120 but using the Commit API instead of PRs
#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note
NONE
```

### CODE REVIEW

File: clients/githubrepo/searchCommits.go [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+	return searchCommitsResponseFrom(resp), nil
+}
+
+func (handler *searchCommitsHandler) buildQuery(request clients.SearchCommitsOptions) (string, error) {
+	if request.Author == "" {
+		return "", fmt.Errorf("%w", errEmptyQuery)
+	}
+	var queryBuilder strings.Builder
+	if _, err := queryBuilder.WriteString(
+		fmt.Sprintf("repo:%s/%s %s",
```
Comment (azeemshaikh38) [inline clients/githubrepo/searchCommits.go:48]: Shouldn't the query be `repo:%s/%s author:%s` ?

File: clients/githubrepo/searchCommits.go [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+
+	resp, _, err := handler.ghClient.Search.Commits(handler.ctx, query, &github.SearchOptions{ListOptions: github.ListOptions{PerPage: 100}})
+	if err != nil {
+		return clients.SearchCommitsResponse{}, fmt.Errorf("Search.Code: %w", err)
+	}
+
+	return searchCommitsResponseFrom(resp), nil
+}
+
+func (handler *searchCommitsHandler) buildQuery(request clients.SearchCommitsOptions) (string, error) {
```
Comment (azeemshaikh38) [inline clients/githubrepo/searchCommits.go:42]: Would be great if you could add some tests for the `buildQuery` fn. See https://github.com/ossf/scorecard/blob/main/clients/githubrepo/search_test.go for example.

File: clients/repo_client.go [hunk 3]
```diff
@@ -44,5 +44,6 @@ type RepoClient interface {
 	ListWebhooks() ([]Webhook, error)
 	ListProgrammingLanguages() ([]Language, error)
 	Search(request SearchRequest) (SearchResponse, error)
+	SearchCommits(request SearchCommitsOptions) (SearchCommitsResponse, error)
```
Comment (azeemshaikh38) [inline clients/repo_client.go:47]: IMO this API should return `[]Commit` so that this API is generic and can be easily extended in the future. I don't want to block this PR for that, so please leave a TODO so that one of us can pick it up later. 

If you can make the change either in this PR or in a future PR that'll be awesome and very much appreciated :)

File: clients/githubrepo/searchCommits.go (hunk 1 above)
Comment (qequ) [reply clients/githubrepo/searchCommits.go]: Added "author:" to the query :+1:

File: clients/githubrepo/searchCommits.go [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+	if request.Author == "" {
+		return "", fmt.Errorf("%w", errEmptyQuery)
+	}
+	var queryBuilder strings.Builder
+	if _, err := queryBuilder.WriteString(
+		fmt.Sprintf("repo:%s/%s %s",
+			handler.repourl.owner, handler.repourl.repo,
+			strings.ReplaceAll(request.Author, "/", " "))); err != nil {
```
[the remark this answers is not in the document]
Comment (qequ) [reply clients/githubrepo/searchCommits.go]: Removed `replaceAll` :+1:

File: clients/githubrepo/searchCommits.go (hunk 2 above)
Comment (qequ) [reply clients/githubrepo/searchCommits.go:42]: Added tests for SearchCommitsHandler's `buildQuery` :+1:

File: clients/githubrepo/client.go [hunk 5]
```diff
@@ -190,6 +194,10 @@ func (client *Client) Search(request clients.SearchRequest) (clients.SearchRespo
 	return client.search.search(request)
 }
 
+func (client *Client) SearchCommits(request clients.SearchCommitsOptions) (clients.SearchCommitsResponse, error) {
```
[the remark this answers is not in the document]
Comment (qequ) [reply clients/githubrepo/client.go:198]: Added comment :+1:

File: clients/repo_client.go (hunk 3 above)
Comment (qequ) [reply clients/repo_client.go]: Updated SearchCommits and now returns `[]Commit` :+1:

**Review by azeemshaikh38 — APPROVED** [review]
Thank you so much for addressing all the comments @qequ! Approved with a comment to remove unused code.

File: clients/search.go [hunk 6]
```diff
@@ -33,3 +33,16 @@ type SearchResponse struct {
...
+}
+
+type SearchCommitsResponse struct {
+	Hits    int
+	Results []SearchCommitResult
+}
+
+type SearchCommitResult struct {
+	ID int64
+}
```
Comment (azeemshaikh38) [inline clients/search.go:48]: Not used anymore and can be removed?

Comment (qequ) [reply clients/search.go]: Removed it :+1:

**Review by azeemshaikh38 — APPROVED** [review]
