### PR TITLE
🐛 Skip CODEOWNERS file in contributors check if there is a parsing error

### LINKED ISSUE #4768: Contributors check fails on CODEOWNERS with ^ character
**Describe the bug**

When running scorecard on the repo: https://github.com/vllm-project/vllm I run into the following error: 

```bash
Error: check runtime error: Contributors: internal error: Client.Repositories.ListContributors: error during contributorsHandler.setup: error during ParseFile: line 55: unexpected character '^' at position 17
2025/08/25 12:22:59 error during command execution: check runtime error: Contributors: internal error: Client.Repositories.ListContributors: error during contributorsHandler.setup: error during ParseFile: line 55: unexpected character '^' at position 17
exit status 1
```

**Reproduction steps**
1. Run scorecards on the repo https://github.com/vllm-project/vllm using the CLI.

**Expected behavior**
The score for the contributors should be computed but instead it is showing a question mark.

**Additional context**
While running the **Contributors** check on [vllm](https://github.com/vllm-project/vllm), the analysis fails due to the `^` character in line 55 of [`.github/CODEOWNERS`](https://github.com/vllm-project/vllm/blob/7b6a8372755dfd6b8b2449b24e2d9d8589ff0291/.github/CODEOWNERS#L55).

The error originates in the `codeowners` package, specifically in [`parseRule`](https://github.com/hmarr/codeowners/blob/b0f609d21eb672b5cb2973f47a80210185102504/parse.go#L134), where `^` is not recognized as a valid pattern character (see [`isPatternChar`](https://github.com/hmarr/codeowners/blob/b0f609d21eb672b5cb2973f47a80210185102504/parse.go#L258)).

Two Potential Solutions:
- Extend the `isPatternChar` function to include `^`.
- Alternatively, implement a patch in the **Scorecards** package to **skip invalid characters** instead of failing.

I’d be happy to contribute a fix, would you recommend modifying the `codeowners` package or adding a patch to Scorecard itself?

### PR DESCRIPTION
**Pull request by juanis2112**
#### What kind of change does this PR introduce?

Bug Fix

- [x] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?
When running scorecard on the repo: https://github.com/IBM/vllm I run into the following error: 

```bash
Error: check runtime error: Contributors: internal error: Client.Repositories.ListContributors: error during contributorsHandler.setup: error during ParseFile: line 55: unexpected character '^' at position 17
2025/08/25 12:22:59 error during command execution: check runtime error: Contributors: internal error: Client.Repositories.ListContributors: error during contributorsHandler.setup: error during ParseFile: line 55: unexpected character '^' at position 17
exit status 1
```

#### What is the new behavior (if this is a feature change)?**

The Codeowners file is skipped if there are parsing errors found so now running scorecard on the repo https://github.com/IBM/vllm shows a score instead of error.

- [ ] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes

Fixes #4768

#### Special notes for your reviewer

I plan to open an issue in the [hmarr/codeowners](https://github.com/hmarr/codeowners/)
 package, as I believe they could benefit from supporting the ^ character in their parsing patterns. Regardless, it’s better for Scorecards to skip the CODEOWNERS file if a parsing error occurs and still produce a score, rather than invalidating the entire check. This change addresses that need.

We could optionally print a message to inform the user that a CODEOWNERS file was skipped, happy to add that if it’s useful.

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note
NONE
```

### CODE REVIEW

File: clients/githubrepo/contributors.go [hunk 1]
```diff
@@ -127,8 +127,7 @@ func mapCodeOwners(handler *contributorsHandler, codeOwnerFile io.ReadCloser, co
 	}
 	ruleset, err := codeowners.ParseFile(codeOwnerFile)
 	if err != nil {
-		handler.errSetup = fmt.Errorf("error during ParseFile: %w", err)
-		return
+		ruleset = nil // skipping CODEOWNERS due to parse error
```
Comment (spencerschrock) [inline clients/githubrepo/contributors.go]: can we add a log that there was a CODEOWNERS parse error?

Similar to some of our other errors:
https://github.com/ossf/scorecard/blob/80ee3ecfedf8b19ab8991713a9fdb2e7dcd7262e/clients/githubrepo/tarball.go#L103-L104

Comment (spencerschrock) [reply clients/githubrepo/contributors.go]: also, leaving the return is probably ok too

Comment (juanis2112) [reply clients/githubrepo/contributors.go]: @spencerschrock  thanks for the review. I'll make the changes! 

Also, the "^" is supported in GitLab but there is no indication that is supported (or not supported) in GitHub. I saw that the vllm-project/vllm fixed it but there are some forks of this project that still have it (like https://github.com/IBM/vllm). Maybe the solution is to remove the "^" in the forks as well.
