### PR TITLE
:bug: Support self-hosted GitLab instances where base URL has a path component

### LINKED ISSUE #3696: Cannot scan self-hosted (private) GitLab repositories
**Describe the bug**
Cannot scan self-hosted (private) GitLab repositories

**Reproduction steps**
1. See screenshot

Shouldnt this be possible acc. to your blogpost?

_You can run Scorecard today on a GitLab.com (or self-hosted GitLab) repository by running Scorecard as you normally would_

https://openssf.org/blog/2023/08/28/openssf-scorecard-launches-v4-12-with-support-for-gitlab/

Thank you!

grafik

### PR DESCRIPTION
**Pull request by spencerschrock**
#### What kind of change does this PR introduce?

bug fix
- [X] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?
Assumes the gitlab API base url doesn't have any part after the domain.

#### What is the new behavior (if this is a feature change)?**
Adds a new environment variable, `GL_HOST` to handle these situations.
The env var is needed, otherwise there's ambiguity over what part of the URL is part of the API url, the repo owner, or project.
 
- [X] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes
Fixes #3696

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note
Fixed a bug which prevented Scorecard from analyzing some self-hosted GitLab repos.
```

### CODE REVIEW

**Comment by spencerschrock** [comment]
@mwager mind testing this?

**Comment by mwager** [comment]
Confirming that this works and scorecard successfully displays the results:

`GL_HOST=https://foo.com/gitlab/ go run main.go --repo https://foo.com/gitlab/org/somerepo`

**Review by naveensrinivasan — APPROVED** [review]
Thanks!

File: clients/gitlabrepo/repo.go [hunk 1]
```diff
@@ -105,7 +126,9 @@ func (r *repoURL) IsValid() error {
 		return fmt.Errorf("%w: %s", errInvalidGitlabRepoURL, r.host)
 	}
 
-	client, err := gitlab.NewClient("", gitlab.WithBaseURL(fmt.Sprintf("%s://%s", r.scheme, r.host)))
+	token := os.Getenv("GITLAB_AUTH_TOKEN")
```
Comment (spencerschrock) [inline clients/gitlabrepo/repo.go:129]: Hmm, this is causing one of the GitLab e2e tests to fail:
```shell
make e2e-gitlab-token
  --- FAIL: TestRepoURL_MakeGitLabRepo (0.92s)
      repo_test.go:177: got https://salsa.debian.org/webmaster-team/webml isgitlab: false expected true
  Scorecard may be missing merge requests when running on non-HEAD of a GitLab repo. Code-Review scores may be lower.
  --- FAIL: TestRepoURL_IsValid (0.05s)
      --- FAIL: TestRepoURL_IsValid/valid_hosted_gitlab_project (1.05s)
          repo_test.go:116: repoURL.IsValid() error = repo unreachable: couldn't reach gitlab instance at salsa.debian.org, wantErr false
          repo_test.go:118: salsa.debian.org/webmaster-team/webwml
```

Will need to debug before this can be merged.

Comment (spencerschrock) [reply clients/gitlabrepo/repo.go]: @mwager can you try once more on the latest commit? 

If it fails, can you repeat your curl command to `https://foo.com/gitlab/api/v4/projects` without the `Authorization` header ([link](https://github.com/ossf/scorecard/issues/3696#issuecomment-1863956617))? What HTTP status code does it throw? 
404? 401?

**Comment by mwager** [comment]
I tested on the latest commit:

grafik

Works like before.

**Comment by spencerschrock** [comment]
> Doing the curl command without the auth header returns 200 with json data...

I've reverted one part to keep the PR smaller. if this causes it to fail for you, i will revert the reversion and merge the current state.

**Comment by mwager** [comment]
Tested again on commit 693712c9, everything fine :)
