### PR TITLE
🐛 Code Review: Use proportional scoring

### LINKED ISSUE #2812: BUG (?): Large changes to Code-Review scores between 4.10.2 and 4.10.5
**Describe the bug**
4.10.5 gives significantly lower scores for Code-Review than 4.10.2. 

I am running Scorecard frequently for some 200 projects. I just upgraded from 4.10.2 to 4.10.5 and noticed that average Code-Review scores are drastically lower: of the 200 projects, 137 saw their score drop. And the average drop (looking only at those projects that dropped) was of ~5 points.

| Δ score | # projects |
| - | - |
| -10	| 3 |
| -9	| 6 |
| -8	| 17 |
| -7	| 14 |
| -6	| 17 |
| -5	| 17 |
| -4	| 8 |
| -3	| 21 |
| -2	| 14 |
| -1	| 20 |
| 0	| 61 |
| 1	| 2 |

**Reproduction steps**
Run Scorecard for the following sample projects with 4.10.2 and 4.10.5:
- https://github.com/pandas-dev/pandas
- https://github.com/systemd/systemd
- http://github.com/microsoft/typescript

Results (trimmed):
--

```json
# pandas @ 4.10.2
    {
      "score": 9,
      "reason": "28 out of last 30 changesets reviewed before merge -- score normalized to 9",
      "name": "Code-Review",
    },
# pandas @ 4.10.5
    {
      "score": 0,
      "reason": "found 2 unreviewed human changesets",
      "name": "Code-Review",
    },
```

```json
# systemd/systemd @ 4.10.2
    {
      "score": 8,
      "reason": "18 out of last 21 changesets reviewed before merge -- score normalized to 8",
      "name": "Code-Review",
    },

# systemd/systemd @ 4.10.5
    {
      "score": 0,
      "reason": "found 3 unreviewed human changesets",
      "name": "Code-Review",
    },
```

```json
# microsoft/typescript @ 4.10.2
    {
      "score": 7,
      "reason": "22 out of last 30 changesets reviewed before merge -- score normalized to 7",
      "name": "Code-Review",
    },

# microsoft/typescript @ 4.10.5
    {
      "score": 0,
      "reason": "found 8 unreviewed human changesets",
      "name": "Code-Review",
    },
```

I intentionally picked these three projects to display here since they are very popular, active and have mature communities. It intuitively seems more likely that 80% of PRs are reviewed than that none are.

Diving in
--

Running the CLI with `--raw` and EXPERIMENTAL_V6=1, I took a look at how commits were handled by both versions.

Here are a few cases from pandas-dev/pandas:

https://github.com/pandas-dev/pandas/pull/52308 was merged without review (author was also merger, so it wasn't an implicit review), but 4.10.5 has a "review: APPROVED by mroeschke" result.

```json
# https://github.com/pandas-dev/pandas/pull/52308 @ 4.10.2
{
   ...
    "results": {
        ...
        "defaultBranchChangesets": [
            ...,
            {
                "number": "52308",
                "reviews": [],
                "authors": [ {
                        "login": "mroeschke"
                    } ],
                "commits": [ {
                        "message": "TYP: Remove unneeded type ignore (#52308)",
                        "sha": "ceef0da443a7bbb608fb0e251f06ae43a809b472",
                        "committer": {
                            "login": "github"
                        }
                    } ]
            },

# https://github.com/pandas-dev/pandas/pull/52308 @ 4.10.5
            {
                "number": "52308",
                "reviews": [ {
                        "state": "APPROVED",
                        "reviewer": {
                            "login": "mroeschke",
                            "isBot": false
                        }
                    } ],
                "authors": [ {
                        "login": "mroeschke",
                        "isBot": false
                    } ],
                "commits": [ {
                        "message": "TYP: Remove unneeded type ignore (#52308)",
                        "sha": "ceef0da443a7bbb608fb0e251f06ae43a809b472",
                        "committer": {
                            "login": "github",
                            "isBot": false
                        }
                    }
                ]
            },
```

https://github.com/pandas-dev/pandas/pull/52316 was reviewed and approved by mroeschke, who then merged it. 4.10.2 presents this correctly, with a review array describing a few comments and then a single approval. 4.10.5, however, shows two approvals by mroeschke. This behavior can be found in a few other PRs.

```json
# https://github.com/pandas-dev/pandas/pull/52316 @ 4.10.2
{
    "number": "52316",
    "platform": "GitHub",
    "reviews": [
        {
            "state": "COMMENTED",
            "reviewer": {
                "login": "mroeschke"
            }
        },
        {
            "state": "COMMENTED",
            "reviewer": {
                "login": "jbrockmendel"
            }
        },
        {
            "state": "APPROVED",
            "reviewer": {
                "login": "mroeschke"
            }
        }
    ],
    "authors": [
        {
            "login": "jbrockmendel"
        }
    ],
    "commits": [
        {
            "message": "PERF: concat_compat (#52316)",
            "sha": "9ba4ef86325abab6029436dcabbe3fab4a60f6ba",
            "committer": {
                "login": "github"
            }
        }
    ]
},

# https://github.com/pandas-dev/pandas/pull/52316 @ 4.10.5
{
    "number": "52316",
    "platform": "GitHub",
    "reviews": [
        {
            "state": "COMMENTED",
            "reviewer": {
                "login": "mroeschke",
                "isBot": false
            }
        },
        {
            "state": "COMMENTED",
            "reviewer": {
                "login": "jbrockmendel",
                "isBot": false
            }
        },
        {
            "state": "APPROVED",
            "reviewer": {
                "login": "mroeschke",
                "isBot": false
            }
        },
        {
            "state": "APPROVED",
            "reviewer": {
                "login": "mroeschke",
                "isBot": false
            }
        }
    ],
    "authors": [ {
            "login": "jbrockmendel",
            "isBot": false
        } ],
    "commits": [ {
            "message": "PERF: concat_compat (#52316)",
            "sha": "9ba4ef86325abab6029436dcabbe3fab4a60f6ba",
            "committer": {
                "login": "github",
                "isBot": false
            }
        } ]
},
```

I suspect that, in 4.10.5, merging a PR is always being considered an approval, even when the author is the same as the merger. However, somehow the Code-Review score in 4.10.5 is lower, not higher...

**Expected behavior**
Unclear? Given the dramatic shift in scores, it seems apparent one of the versions (4.10.2 or 4.10.5) is/was giving incorrect results. I intuitively suspect 4.10.2 is correct, but I could be wrong? 🤷‍♂️

**Additional context**
#2798 would be useful here. Having information of how different PRs/commits are categorized would make debugging and comprehending this sort of thing much easier.

Shoutout to @gabibguti, who helped me do this initial exploration of this behavior.

### PR DESCRIPTION
**Pull request by raghavkaul**
#### What kind of change does this PR introduce?
Revert Code-Review check to proportional scoring.

#### What is the current behavior?
Currently, Code-Review works like this:
If the only commit activity is by bots, we return inconclusively
If any number of bot code changes are unreviewed, the score drops 3 points
If ==1 human change is unreviewed, the score drops by 7 points
If >1 human change is unreviewed, the score drops to 0

#### What is the new behavior (if this is a feature change)?**
This takes Code-Review back to proportional scoring
If the only commit activity is by bots, we return inconclusively 
If there is human and bot commit activity, but only bot commits are unreviewed, the score drops by 3 points
If all bot commits are reviewed, the score is based on the proportion of human commits that are unreviewed

#### Which issue(s) this PR fixes
Fixes #2812 .

#### Does this PR introduce a user-facing change?
```release-note
* Code-Review: Use proportional instead of leveled scoring.
```

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
Isn't this the fix for https://github.com/ossf/scorecard/issues/2812?

**Comment by raghavkaul** [comment]
@naveensrinivasan Yes! Typo - fixed.

File: checks/evaluation/code_review.go [hunk 1]
```diff
@@ -109,5 +105,13 @@ func reviewScoreForChangeset(changeset *checker.Changeset) (score reviewScore) {
 		}
 	}
 
+	dl.Info(
+		&checker.LogMessage{
+			Text: fmt.Sprintf(
+				"couldn't find approvals for revision: %s platform: %s",
```
Comment (spencerschrock) [inline checks/evaluation/code_review.go:111]: note: this displays the following for commits unassociated with a PR/MR.
Should we have a value for when no review platform detected?
```
        "Info: couldn't find approvals for revision: cf79bed7ddc85c762a291400f904d18fbbf14581 platform: ",
        "Info: couldn't find approvals for revision: aca3970538e89a86be9968052615ae5ed05d9259 platform: ",
        "Info: couldn't find approvals for revision: 8496c8c8f2f9027d4ba12ce1e5f7a79b52fd29e9 platform: ",
```

File: e2e/code_review_test.go [hunk 2]
```diff
@@ -23,42 +23,16 @@ import (
...
-				NumberOfInfo:  0,
-				NumberOfDebug: 0,
-			}
-			result := checks.CodeReview(&req)
-			Expect(scut.ValidateTestReturn(nil, "use code reviews", &expected, &result, &dl)).Should(BeTrue())
-			Expect(repoClient.Close()).Should(BeNil())
-		})
 		It("Should return use of code reviews at commit", func() {
 			dl := scut.TestDetailLogger{}
-			repo, err := githubrepo.MakeGithubRepo("ossf-tests/airflow")
```
[the remark this answers is not in the document]
Comment (raghavkaul) [reply e2e/code_review_test.go:61]: Yes, there are no pull requests on our fork, and the GH API doesn't follow pull requests to the original repo - so this would never have detected any pull requests or reviews.

File: checks/evaluation/code_review.go [hunk 3]
```diff
@@ -69,33 +69,29 @@ func CodeReview(name string, dl checker.DetailLogger, r *checker.CodeReviewData)
 	}
```
[the remark this answers is not in the document]
Comment (raghavkaul) [reply checks/evaluation/code_review.go:69]: Yes, you're right - in that scenario, it should be 0/10 instead of ?/10.

[the remark this answers is not in the document]
Comment (raghavkaul) [reply checks/evaluation/code_review.go]: `e2e/code_review_test.go:L79` should now capture that scenario.

File: checks/evaluation/code_review.go (hunk 1 above)
Comment (raghavkaul) [reply checks/evaluation/code_review.go:112]: Added `committed directly`

File: checks/evaluation/code_review.go [hunk 4]
```diff
@@ -39,81 +38,57 @@ func CodeReview(name string, dl checker.DetailLogger, r *checker.CodeReviewData)
...
+		return checker.CreateProportionalScoreResult(
 			name,
-			fmt.Sprintf("found %v unreviewed human changesets", nUnreviewedHumanChanges),
-			score,
+			fmt.Sprintf(
+				"found %d unreviewed changesets out of %d", nUnreviewedHumanChanges,
+				nHumanChangesTotal,
+			),
+			nHumanChangesTotal-nUnreviewedHumanChanges,
+			nHumanChangesTotal,
```
Comment (spencerschrock) [inline checks/evaluation/code_review.go:84]: Just to be clear, is it intentional is to ignore all unreviewed bot PRs in this score?

It leads to scenarios where having an unreviewed human PR could increase your score.
Imagine 30 PRs:
29 reviewed human PRs, and 1 unreviewed bot PRs. This would score a 7

If instead we have 28 reviewed human, 1 unreviewed human and 1 unreviewed bot, the score would now be a 28/29, which I think would be a 9.

**Review by spencerschrock — COMMENTED** [review]
If this is the desired scoring scheme, I think this PR looks good, but I think we should agree on the scoring though before merging as it seems like Azeem had different ideas in #2450 around if unreviewed bot PRs should be weighed differently.

I think the two approaches were:
1. This sort of leveled scoring where an unreviewed bot PR drops the score to 7
2. Just ignore reviewed (dependa)bot PRs to address the original problem in #2450, but otherwise use the same reviewed / total scoring we used before.

```
score = reviewed human / (reviewed human + any unreviewed )
```

I think there's value in the simplicity of 2, as we've had a few accidental scoring situations coding up this implementation. But ultimately I think we can come up with hypothetical "what if" scoring situations either way.

File: checks/evaluation/code_review.go (hunk 4 above)
Comment (raghavkaul) [reply checks/evaluation/code_review.go:75]: Yes, it's intentional to ignore all unreviewed bot PRs. Changed this so that the -3 penalty is no longer applied.

File: checks/evaluation/code_review.go [hunk 5]
```diff
@@ -39,84 +38,48 @@ func CodeReview(name string, dl checker.DetailLogger, r *checker.CodeReviewData)
...
-		case isReviewed && !isBotCommit:
-			foundHumanReviewActivity = true
-		case !isReviewed && isBotCommit:
-			nUnreviewedBotChanges += 1
-			unreviewedBotRevisionIDs = append(unreviewedBotRevisionIDs, cs.RevisionID)
-		case !isReviewed && !isBotCommit:
-			nUnreviewedHumanChanges += 1
-			unreviewedHumanRevisionIDs = append(unreviewedHumanRevisionIDs, cs.RevisionID)
+		isReviewed := reviewScoreForChangeset(cs, dl) >= changesReviewed
+		if cs.Author.IsBot {
```
Comment (spencerschrock) [inline checks/evaluation/code_review.go:52]: doesn't this ignore unreviewed bot PRs as well?

File: checks/evaluation/code_review.go [hunk 6]
```diff
@@ -130,5 +93,17 @@ func reviewScoreForChangeset(changeset *checker.Changeset) (score reviewScore) {
 		}
 	}
 
+	plat := changeset.ReviewPlatform
+	if plat == "" {
+		plat = checker.ReviewPlatformUnknown
+	}
```
Comment (spencerschrock) [inline checks/evaluation/code_review.go:99]: Would it be better to set the platform to known here:
https://github.com/ossf/scorecard/blob/332472d4d67be05f151151244ed3aa3da8d3f975/checks/raw/code_review.go#L127-L145

Instead of adding the logic here?

File: checks/evaluation/code_review_test.go [hunk 7]
```diff
@@ -84,7 +84,7 @@ func TestCodeReview(t *testing.T) {
 		{
 			name: "all human changesets reviewed, missing review on bot changeset",
 			expected: scut.TestReturn{
-				Score:         7,
+				Score:         10,
```
Comment (spencerschrock) [inline checks/evaluation/code_review_test.go:87]: also related to not penalizing unreviewed bot prs

File: checks/evaluation/code_review.go [hunk 8]
```diff
@@ -127,5 +102,17 @@ func reviewScoreForChangeset(changeset *checker.Changeset) (score reviewScore) {
 		}
 	}
 
+	plat := changeset.ReviewPlatform
+	if plat == "" {
+		plat = "committed directly"
+	}
```
[the remark this answers is not in the document]
Comment (raghavkaul) [reply checks/evaluation/code_review.go]: Changed to `changeset.Unknown`

File: checks/evaluation/code_review.go [hunk 9]
```diff
@@ -39,89 +39,60 @@ func CodeReview(name string, dl checker.DetailLogger, r *checker.CodeReviewData)
...
-			foundHumanReviewActivity = true
-		case !isReviewed && isBotCommit:
-			nUnreviewedBotChanges += 1
-			unreviewedBotRevisionIDs = append(unreviewedBotRevisionIDs, cs.RevisionID)
-		case !isReviewed && !isBotCommit:
-			nUnreviewedHumanChanges += 1
-			unreviewedHumanRevisionIDs = append(unreviewedHumanRevisionIDs, cs.RevisionID)
+		isReviewed := reviewScoreForChangeset(cs, dl) >= changesReviewed
+		if isReviewed && cs.Author.IsBot {
+			continue // ignore reviewed bot commits
```
Comment (spencerschrock) [inline checks/evaluation/code_review.go:55]: should the comment have a link to the issue?

File: checks/evaluation/code_review.go [hunk 10]
```diff
@@ -39,89 +39,60 @@ func CodeReview(name string, dl checker.DetailLogger, r *checker.CodeReviewData)
...
 			name,
 			fmt.Sprintf(
-				"found %v unreviewed human changesets (%d total)",
-				nUnreviewedHumanChanges, len(r.DefaultBranchChangesets),
+				"found %d unreviewed changesets out of %d", nUnreviewedChanges,
+				nChanges,
 			),
-			score,
+			int(math.Max(float64(nChanges-nUnreviewedChanges), 0)),
+			nChanges,
```
Comment (spencerschrock) [inline checks/evaluation/code_review.go:81]: nit: are these lines long enough to need the break?

File: e2e/code_review_test.go [hunk 11]
```diff
@@ -32,34 +32,9 @@ import (
...
-				NumberOfDebug: 1,
-			}
-			result := checks.CodeReview(&req)
-			Expect(scut.ValidateTestReturn(nil, "use code reviews", &expected, &result, &dl)).Should(BeTrue())
-			Expect(repoClient.Close()).Should(BeNil())
-		})
 		It("Should return use of code reviews at commit", func() {
 			dl := scut.TestDetailLogger{}
-			repo, err := githubrepo.MakeGithubRepo("ossf-tests/airflow")
+			repo, err := githubrepo.MakeGithubRepo("apache/airflow")
```
Comment (spencerschrock) [inline e2e/code_review_test.go:37]: should we use `ossf-tests/scorecard-attestor-code-review-e2e` here too?

**Review by spencerschrock — APPROVED** [review]

File: e2e/code_review_test.go (hunk 11 above)
Comment (raghavkaul) [reply e2e/code_review_test.go:37]: The `ossf-tests` code review repo is erroring for me, will update this test in a follow-up.
