### PR TITLE
:bug: Fix OSV URI in probe remediation text

### LINKED ISSUE #3609: Fix URI in OSVVulnerability probe
See https://github.com/ossf/scorecard/pull/3487#discussion_r1372117029

### PR DESCRIPTION
**Pull request by spencerschrock**
#### What kind of change does this PR introduce?

bug fix

- [X] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?
The OSV IDs are joined together when generating a link, leading to a broken link:
For example, if a vuln is known by both `foo` and `bar`, the link was `https://osv.dev/bar,foo` which is broken, but `https://osv.dev/bar` or `https://osv.dev/foo` would have worked.

#### What is the new behavior (if this is a feature change)?**
The first Vuln ID is used for the link, from the example above that leads to `https://osv.dev/bar`
Also added a space after the link, so the period wouldn't be interpreted as part of the link in the remediation text.

- [X] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes
Fixes #3609

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note
NONE
```

### CODE REVIEW

File: probes/hasOSVVulnerabilities/impl.go [hunk 1]
```diff
@@ -65,10 +68,12 @@ func Run(raw *checker.RawResults) ([]finding.Finding, string, error) {
 		if err != nil {
 			return nil, Probe, fmt.Errorf("create finding: %w", err)
 		}
-		f = f.WithMessage(fmt.Sprintf("Project is vulnerable to: %s",
-			strings.Join(vuln.IDs, " / ")))
+		f = f.WithMessage("Project is vulnerable to: " + strings.Join(vuln.IDs, " / "))
+		if len(vuln.IDs) == 0 {
+			return nil, Probe, errNoVulnID
+		}
```
Comment (pnacht) [inline probes/hasOSVVulnerabilities/impl.go:74]:
```suggestion
		if len(vuln.IDs) == 0 {
			return nil, Probe, errNoVulnID
		}
		f = f.WithMessage("Project is vulnerable to: " + strings.Join(vuln.IDs, " / "))
```

Since `f` won't be used if we enter the `if` block.

Comment (spencerschrock) [reply probes/hasOSVVulnerabilities/impl.go]: Done in 60c806e3deeada7b970701dffc6cc8828b6bb955, except I moved it slightly higher so we don't create `f` at all.

**Review by naveensrinivasan — APPROVED** [review]
