### PR TITLE
:book: add error clarification for github branch protection errors

### LINKED ISSUE #3498: error: Branch-Protection: internal error: error during branch protection check
**Describe the bug**

error during command execution: check runtime error: Branch-Protection: internal error: error during branchesHandler.setup: internal error: githubv4.Query: Resource not accessible by personal access token
 
 
**Reproduction steps**
1. Create a new GitHub PAT token with public repo access 
2. Run scorecard from the latest Docker image on any GItHub repo
3.  observe error
 
**Expected behavior**
no errors -> scorecard  generated 

**Additional context**
Actual behaviour  - getting error on Branch Protection checks

```
docker run -e GITHUB_TOKEN=github_pat_xxxxxxxxxxxxxxx gcr.io/openssf/scorecard --repo https://github.com/ossf/scorecard

Starting [CII-Best-Practices]
Starting [Security-Policy]
Starting [Fuzzing]
Starting [Branch-Protection]
Starting [Pinned-Dependencies]
Starting [Token-Permissions]
Starting [CI-Tests]
Starting [Packaging]
Starting [Maintained]
Starting [SAST]
Starting [Dangerous-Workflow]
Starting [License]
Starting [Code-Review]
Starting [Contributors]
Starting [Signed-Releases]
Starting [Vulnerabilities]
Starting [Dependency-Update-Tool]
Starting [Binary-Artifacts]

Error: check runtime error: Branch-Protection: internal error: error during branchesHandler.setup: internal error: githubv4.Query: Resource not accessible by personal access token
2023/09/20 09:27:54 error during command execution: check runtime error: Branch-Protection: internal error: error during branchesHandler.setup: internal error: githubv4.Query: Resource not accessible by personal access token


```

### PR DESCRIPTION
**Pull request by spencerschrock**
#### What kind of change does this PR introduce?

doc update in the form of error message

- [X] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?
Users get a vague message "internal error: githubv4.Query: Resource not accessible"

#### What is the new behavior (if this is a feature change)?**
Users get a more specific error message and link to debug:

"internal error: some github tokens cant read classic branch protection rules: https://github.com/ossf/scorecard-action/blob/main/docs/authentication/fine-grained-auth-token.md"

- [ ] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes
Fixes #3498

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note
NONE
```

### CODE REVIEW

File: clients/githubrepo/branches.go [hunk 1]
```diff
@@ -31,6 +31,8 @@ import (
 
 const (
 	refPrefix = "refs/heads/"
+	//nolint:lll
+	classicBranchErrMsg = "some github tokens cant read classic branch protection rules: https://github.com/ossf/scorecard-action/blob/main/docs/authentication/fine-grained-auth-token.md"
```
Comment (justaugustus) [inline clients/githubrepo/branches.go]:
```suggestion
	classicBranchErrMsg = "some github tokens can't read classic branch protection rules: https://github.com/ossf/scorecard-action/blob/main/docs/authentication/fine-grained-auth-token.md"
```

**Review by justaugustus — CHANGES_REQUESTED** [review]
One nit, but looks good otherwise.
Thanks @spencerschrock!
