### PR TITLE
:bug: trip surrounding quotes that may have been added by extractCommand

### LINKED ISSUE #4733: BUG: Pinned-Dependency for downloadThenRun finding when GitHub Raw Commit Hash Used
**Describe the bug**
With https://github.com/ossf/scorecard/pull/3694 merged, a GitHub pinned hash should not be marked as an unpinned dependency.

**Reproduction steps**
1. Create a Dockerfile in an empty directory (this example is for `rustup`)

```Dockerfile
FROM public.ecr.aws/docker/library/python:3.13.5-alpine3.21@sha256:c9a09c45a4bcc618c7f7128585b8dd0d41d0c31a8a107db4c8255ffe0b69375d

# Install system dependencies and Python package manager
RUN apk update && \
    apk add --no-cache --virtual .build-deps \
    build-base \
    gcc \
    musl-dev \
    libffi-dev \
    openssl-dev \
    curl

# Install Rust and Cargo with a newer version that supports edition2024
RUN curl --proto '=https' --tlsv1.2 -sSf 'https://raw.githubusercontent.com/rust-lang/rustup/f7935a8ad24a445629ceedb2cb706a4469e1e5b3/rustup-init.sh' | sh -s -- -v -y --default-toolchain nightly-2025-07-30 && \
    . $HOME/.cargo/env && \
    rustup default nightly-2025-07-30
```

2. Run
```sh
docker run -it --rm --env GITHUB_AUTH_TOKEN="$GITHUB_AUTH_TOKEN" -v `pwd`:`pwd` -w `pwd` --privileged gcr.io/openssf/scorecard:stable --checks "Pinned-Dependencies" --show-annotations --show-details --verbosity debug --format json --local .`
```

3. See the `downloadThenRun` finding

```json                  
{
    "date": "2025-07-30T22:17:48Z",
    "repo": {
        "name": "file://.",
        "commit": "unknown"
    },
    "scorecard": {
        "version": "v5.1.1-45-g40bbc9c9",
        "commit": "40bbc9c958aa66327fb026b2136f1951298ca0f8"
    },
    "score": 5.0,
    "checks": [
        {
            "details": [
                "Warn: downloadThenRun not pinned by hash: Dockerfile:14-16",
                "Info:   1 out of   1 containerImage dependencies pinned",
                "Info:   0 out of   1 downloadThenRun dependencies pinned"
            ],
            "score": 5,
            "reason": "dependency not pinned by hash detected -- score normalized to 5",
            "name": "Pinned-Dependencies",
            "documentation": {
                "url": "https://github.com/ossf/scorecard/blob/40bbc9c958aa66327fb026b2136f1951298ca0f8/docs/checks.md#pinned-dependencies",
                "short": "Determines if the project has declared and pinned the dependencies of its build process."
            }
        }
    ],
    "metadata": null
}
```

**Expected behavior**
No findings when pinned against the GitHub commit hash.

**Additional context**

### PR DESCRIPTION
**Pull request by Fix3dP0int**
#### What kind of change does this PR introduce?

bug fix
(Is it a bug fix, feature, docs update, something else?)

- [x] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?

  - URLs surrounded by quotes are ignored/missed
  - Commands like curl 'https://example.com/script.sh' don't get flagged for unpinned dependencies

#### What is the new behavior (if this is a feature change)?**

  - URLs surrounded by single quotes ('https://example.com') are properly detected
  - URLs surrounded by double quotes ("https://example.com") are properly detected
  - URLs without quotes continue to work as before
  - Proper pinning validation now works for all quote styles

- [x] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes

Fixes #4733 

#### Does this PR introduce a user-facing change?

No.

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note
:bug: trip surrounding quotes that may have been added by extractCommand
```

### CODE REVIEW

File: checks/raw/shell_download_validate.go [hunk 1]
```diff
@@ -303,7 +303,14 @@ func hasUnpinnedURLs(cmd []string) bool {
 
 	// Extract any URLs passed to the download utility
 	for _, s := range cmd {
-		u, err := url.ParseRequestURI(s)
+		// Strip surrounding quotes that may have been added by extractCommand
+		cleanArg := s
```
Comment (spencerschrock) [inline checks/raw/shell_download_validate.go:307]: this is just one spot `extractCommand` feeds into. My initial thought is "can we just remove the extra quotes from extractCommand?" I haven't looked into what it would break.

Comment (gcanlin) [reply checks/raw/shell_download_validate.go:307]: I test the removal from extractCommand, but it will take some breaking changes. Removing quotes from extractCommand exposed a bug where the code incorrectly flags local file executions (like
  `bash -c "file2"`) as insecure downloads. We can add more handling logics to fix the bug. But I think it's more complex than just adding the removal in `hasUnpinnedURLs`.

**Comment by spencerschrock** [comment]
Back from vacation, going through my backlog from before and reopenning stale PRs
