### PR TITLE
🐛 Prevent partial cron transfers caused by controller failures

### LINKED ISSUE #2307: Missing BigQuery data
**Describe the bug**
The cron job has partial results for the 9/19 partition.

**Reproduction steps**
Not user reproducible, but occurs when the controller crashes without publishing shard metadata.

**Expected behavior**
Every weekly cron produces complete data.

**Additional context**
1. the controller started, and pushed some subset of messages to the pubsub topic (at least 109k shards of the expected 124k were pushed). Batch 1
2. the controller crashed within the first 12 seconds. and the shard metadata file was never created
3. the controller restarted and pushed another 124k shards to the pubsub topic. Batch 2
4. the workers tried to work on all 200k+ requests and only finished when the messages died after 1 week in the pubsub

This leads to two bugs:
1. the bq transfer tool transferred partial results on Thursday since the first batch didn't have a metadata file
2. the bq transfer tool never transferred results for batch 2 because workers only processed 10% of the batch 2 shards which is less than the transfer threshold.

### PR DESCRIPTION
**Pull request by spencerschrock**
#### What kind of change does this PR introduce?

Bug fix

- [X] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?
See #2307 for details.

#### What is the new behavior (if this is a feature change)?**
1. the BQ transfer tool will not transfer results for jobs without a `.shard_metadata` file.
2. cron workers won't process requests for jobs without a `.shard_metadata` file.

Note: This makes assumptions about how the pubsub subscription is configured, namely that messages redeliveries are limited. The default value (5 re-tries) works, and is currently being used by scorecardcron.

- [X] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes
#2307 

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note
NONE
```

### CODE REVIEW

File: cron/internal/bq/main_test.go [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+package main
+
+import (
+	"testing"
+)
+
+func TestIsCompleted(t *testing.T) {
```
Comment (azeemshaikh38) [inline cron/internal/bq/main_test.go:21]: Would be very helpful if we added tests for `getBucketSummary` fn. Can do in a separate PR.

**Review by azeemshaikh38 — APPROVED** [review]
Thanks! Great finds :)

File: cron/internal/bq/main_test.go (hunk 1 above)
Comment (azeemshaikh38) [reply cron/internal/bq/main_test.go:21]: Resolving so we can merge.
