### PR TITLE
🐛 Licenses: Get License SPDXId from GitLab API

### LINKED ISSUE #3333: BUG: Apache 2.0 license not recognized
**Describe the bug**
When having the Apache 2.0 license placed at the root of a GitLab repo, it is not recognized as an "FSF or OSI recognized license"

**Reproduction steps**
1. Place Apache 2.0 license (c.f. https://www.apache.org/licenses/LICENSE-2.0.html) at the root of the repo
2. Run `export SCORECARD_EXPERIMENTAL=1`
3. Run `export GITLAB_AUTH_TOKEN=<token>`
4. Run `scorecard --repo https://gitlab.com/<namespace>/<repo> --commit <commit id> --checks=License,Code-Review,Maintained,Security-Policy,Binary-Artifacts,Vulnerabilities,Pinned-Dependencies --show-details`
5. Observe output about license, telling a score 9/10 and saying: 
```
Info: License file found in expected location: LICENSE:1  
Warn: Any licence detected not an FSF or OSI recognized license: LICENSE:1
```

**Expected behavior**
Getting a 10/10 rating with no complaints.

**Additional context**
Scorecard version: v4.11.0
Reproduced on: Debian 11.x x86 architecure, macOS Ventura ARM architecture

### PR DESCRIPTION
**Pull request by raghavkaul**
#### What kind of change does this PR introduce?
Updates the GitLab client so that we can get SPDXId from the GitLab API. A software license's SPDXId allows us to determine whether a GitLab repo's License is FSF/OSI-recognized, and get the last 1/10 points on the License check, which was previously impossible for GitLab repos.

Fixes #3333.

### CODE REVIEW

File: clients/gitlabrepo/licenses.go [hunk 1]
```diff
@@ -44,33 +44,27 @@ var errLicenseURLParse = errors.New("couldn't parse gitlab repo license url")
...
-		if len(licenseMap) == 0 {
-			// TODO: handler.errSetup = fmt.Errorf("request for repo licenses failed with %w", err)
-			handler.errSetup = fmt.Errorf("%w: ListLicenses not yet supported for gitlab", clients.ErrUnsupportedFeature)
-			return
-		}
-
 		l := handler.glProject.License
 
-		ptn, err := regexp.Compile(fmt.Sprintf("%s/~/blob/master/(.*)", handler.repourl.URI()))
+		ptn, err := regexp.Compile(fmt.Sprintf("%s/-/blob/(\\w+)/(.*)", handler.repourl.URI()))
```
Comment (spencerschrock) [inline clients/gitlabrepo/licenses.go:49]: do we need to the branch as one of the capture groups if we dont use it?

As opposed to something like: `(?:\\w+)`

**Review by spencerschrock — APPROVED** [review]
