### PR TITLE
🐛 GitLab: Fix URI() used for OSS-Fuzz detection

### LINKED ISSUE #3476: BUG: Fuzzing check doesn't detect OSS-Fuzz for GitLab repos
**Describe the bug**
GitLab repos that are registered in OSS-Fuzz don't get Fuzzing credit in Scorecard.

Ex. libtiff in deps.dev: https://deps.dev/project/gitlab/libtiff%2Flibtiff

Has a project.yaml in oss-fuzz here: https://github.com/google/oss-fuzz/blob/master/projects/libtiff/project.yaml
But this repo gets 0/10 in the Fuzzing check.

### PR DESCRIPTION
**Pull request by raghavkaul**
#### What kind of change does this PR introduce?
Update URI() for GitLab repo client. Previously, it used the numeric project ID, which isn't the actual URI.

Fixes #3476.

### CODE REVIEW

File: e2e/fuzzing_test.go [hunk 1]
```diff
@@ -60,6 +61,38 @@ var _ = Describe("E2E TEST:"+checks.CheckFuzzing, func() {
 			Expect(repoClient.Close()).Should(BeNil())
 			Expect(ossFuzzRepoClient.Close()).Should(BeNil())
 		})
+		It("Should return use of OSS-Fuzz - GitLab", func() {
```
Comment (spencerschrock) [inline e2e/fuzzing_test.go:64]: Does it matter if this runs with the GitHub integration or the GitLab ones, or both? 
Since this uses the ossfuzz client, I don't think so, but I know some of the gitlab repo init stuff reaches out to the network.

Feel free to resolve, I think the answer is no, but wanted to post.

**Review by spencerschrock — APPROVED** [review]

File: e2e/fuzzing_test.go (hunk 1 above)
Comment (raghavkaul) [reply e2e/fuzzing_test.go:64]: This test shouldn't make a request to either GitHub or GitLab (OSS Fuzz results are fetched from the GCS bucket). But it does connect to the network, and is a GitLab-specific test, so I opted to leave it as an E2E test with the ` - GitLab` marker.
