### PR TITLE
:bug: Updated checks arguments to be case insensitive

### LINKED ISSUE #674: BUG - Checks are case sensitive
**Describe the bug**
The `checks` are case-sensitive. `go run .  --repo=github.com/ossf/scorecard  --checks=code-review`. This causes the command line to ignore the check that was supposed to `Code-Review`

**Expected behavior**
The checks have to be case-insensitive. 

**Additional context**
Related code https://github.com/ossf/scorecard/blob/main/cmd/root.go#L115

### PR DESCRIPTION
**Pull request by notanton**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fixes #674

* **What is the current behavior?** (You can also link to an open issue here)
`checks` arguments are case sensitive

* **What is the new behavior (if this is a feature change)?**
`checks` arguments are no longer case sensitive

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

### CODE REVIEW

File: checks/all_checks.go [hunk 1]
```diff
@@ -14,11 +14,13 @@
 
 package checks
 
+import "strings"
```
Comment (naveensrinivasan) [inline checks/all_checks.go:17]: Can you please combine these imports?
```
import(
"strings"
"github.com/ossf/scorecard/checker")
```

This will get rid of the lint failures.

**Review by naveensrinivasan — COMMENTED** [review]
Thanks, @notanton for the contribution!  Can you please resolve the conflict and the import statement? Then it should be good to be merged.

**Review by azeemshaikh38 — CHANGES_REQUESTED** [review]
This PR will break this line here: https://github.com/ossf/scorecard/blob/main/cron/worker/main.go#L183

File: cmd/root.go [hunk 2]
```diff
@@ -118,8 +118,9 @@ or ./scorecard --{npm,pypi,rubgems}=<package_name> [--checks=check1,...] [--show
 		enabledChecks := checker.CheckNameToFnMap{}
 		if len(checksToRun) != 0 {
 			for _, checkToRun := range checksToRun {
-				if checkFn, ok := checks.AllChecks[checkToRun]; ok {
-					enabledChecks[checkToRun] = checkFn
+				checkIndex := strings.ToLower(checkToRun)
```
Comment (azeemshaikh38) [inline cmd/root.go:121]: We can update this code to:

```
for _, checkToRun := range checksToRun {
  for key, checkFn := range checks.AllChecks {
    if strings.ToLower(checkToRun) == strings.ToLower(key) {
     enabledChecks[key] = checkFn
   }
  }  
}
```

Then the rest of the code can remain the same.

Comment (notanton) [reply cmd/root.go]: Thanks @azeemshaikh38. I have made the above change and removed the need to index check functions with the lower case key so that constants like `checks.CheckBranchProtection` remain to work if we need to delete functions from the map, as in the case https://github.com/ossf/scorecard/blob/main/cron/worker/main.go#L183

File: cmd/root.go [hunk 3]
```diff
@@ -117,12 +117,15 @@ or ./scorecard --{npm,pypi,rubgems}=<package_name> [--checks=check1,...] [--show
 
 		enabledChecks := checker.CheckNameToFnMap{}
 		if len(checksToRun) != 0 {
+		loop:
 			for _, checkToRun := range checksToRun {
-				if checkFn, ok := checks.AllChecks[checkToRun]; ok {
-					enabledChecks[checkToRun] = checkFn
-				} else {
-					log.Fatalf("Invalid check: %s", checkToRun)
+				for key, checkFn := range checks.AllChecks {
```
Comment (azeemshaikh38) [inline cmd/root.go:122]: Instead of `continue loop`, put the nested `for` inside a fn:

```
for _, checkToRun := range checksToRun {
  if b := parseCheckName(checkToRun, &enabledChecks); b == false {
    log.Fatalf("Invalid check: %s", checkToRun)
  }
}
```

**Review by azeemshaikh38 — APPROVED** [review]

**Review by naveensrinivasan — APPROVED** [review]
