### PR TITLE
:seedling: Upgrade to buildkit 0.10.3

### LINKED ISSUE #1725: BUG -  Upgrade to buildkit 0.10.0 fails because of Unit test failures
**Describe the bug**
BUG -  Upgrade to buildkit 0.10.0 fails because of Unit test failures

https://github.com/ossf/scorecard/pull/1722

```
2022/03/11 15:37:45 Non-pinned dockerfile:   utests.TestReturn{
[32](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:32)
  	Error:         nil,
[33](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:33)
- 	Score:         0,
[34](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:34)
+ 	Score:         10,
[35](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:35)
- 	NumberOfWarn:  1,
[36](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:36)
+ 	NumberOfWarn:  0,
[37](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:37)
- 	NumberOfInfo:  0,
[38](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:38)
+ 	NumberOfInfo:  1,
[39](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:39)
  	NumberOfDebug: 0,
[40](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:40)
  }
[41](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:41)

[42](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:42)
2022/03/11 15:37:45 Pinned dockerfile as:   utests.TestReturn{
[43](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:43)
  	Error:         nil,
[44](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:44)
- 	Score:         10,
[45](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:45)
+ 	Score:         0,
[46](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:46)
- 	NumberOfWarn:  0,
[47](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:47)
+ 	NumberOfWarn:  1,
[48](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:48)
- 	NumberOfInfo:  1,
[49](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:49)
+ 	NumberOfInfo:  0,
[50](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:50)
  	NumberOfDebug: 0,
[51](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:51)
  }
[52](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:52)

[53](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:53)
2022/03/11 15:37:45 Non-pinned dockerfile as:   utests.TestReturn{
[54](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:54)
  	Error:         nil,
[55](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:55)
- 	Score:         0,
[56](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:56)
+ 	Score:         10,
[57](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:57)
- 	NumberOfWarn:  2,
[58](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:58)
+ 	NumberOfWarn:  0,
[59](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:59)
- 	NumberOfInfo:  0,
[60](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:60)
+ 	NumberOfInfo:  1,
[61](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:61)
  	NumberOfDebug: 0,
[62](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:62)
  }
[63](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:63)

[64](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:64)
--- FAIL: TestDockerfilePinning (0.00s)
[65](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:65)
    --- FAIL: TestDockerfilePinning/Non-pinned_dockerfile (0.02s)
[66](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:66)
    --- FAIL: TestDockerfilePinning/Pinned_dockerfile_as (0.01s)
[67](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:67)
    --- FAIL: TestDockerfilePinning/Non-pinned_dockerfile_as (0.00s)
[68](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:68)
2022/03/11 15:37:45 Dockerfile with args:   utests.TestReturn{
[69](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:69)
  	Error:         nil,
[70](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:70)
- 	Score:         0,
[71](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:71)
+ 	Score:         10,
[72](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:72)
- 	NumberOfWarn:  2,
[73](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:73)
+ 	NumberOfWarn:  0,
[74](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:74)
- 	NumberOfInfo:  0,
[75](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:75)
+ 	NumberOfInfo:  1,
[76](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:76)
  	NumberOfDebug: 0,
[77](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:77)
  }
[78](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:78)

[79](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:79)
2022/03/11 15:37:45 Pinned dockerfile as no hash:   utests.TestReturn{
[80](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:80)
  	Error:         nil,
[81](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:81)
  	Score:         0,
[82](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:82)
- 	NumberOfWarn:  4,
[83](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:83)
+ 	NumberOfWarn:  1,
[84](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:84)
  	NumberOfInfo:  0,
[85](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:85)
  	NumberOfDebug: 0,
[86](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:86)
  }
[87](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:87)

[88](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:88)
--- FAIL: TestDockerfilePinningWihoutHash (0.00s)
[89](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:89)
    --- FAIL: TestDockerfilePinningWihoutHash/Dockerfile_with_args (0.00s)
[90](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:90)
        pinned_dependencies_test.go:799: test failed: log message not present: {Error:<nil> Score:0 NumberOfWarn:2 NumberOfInfo:0 NumberOfDebug:0}
[91](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:91)
    --- FAIL: TestDockerfilePinningWihoutHash/Pinned_dockerfile_as_no_hash (0.00s)
[92](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:92)
--- FAIL: TestDockerfileInsecureDownloadsLineNumber (0.00s)
[93](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:93)
    --- FAIL: TestDockerfileInsecureDownloadsLineNumber/dockerfile_downloads (0.00s)
[94](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:94)
        pinned_dependencies_test.go:639: test failed: log message not present: [{snippet:curl bla | bash startLine:35 endLine:36} {snippet:pip install -r requirements.txt startLine:41 endLine:42}]
[95](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:95)
        pinned_dependencies_test.go:639: test failed: log message not present: [{snippet:curl bla | bash startLine:35 endLine:36} {snippet:pip install -r requirements.txt startLine:41 endLine:42}]
[96](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:96)
    --- FAIL: TestDockerfileInsecureDownloadsLineNumber/dockerfile_downloads_multi-run (0.00s)
[97](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:97)
        pinned_dependencies_test.go:639: test failed: log message not present: [{snippet:/tmp/file3 startLine:28 endLine:28} {snippet:/tmp/file1 startLine:30 endLine:30} {snippet:bash /tmp/file3 startLine:32 endLine:34} {snippet:bash /tmp/file1 startLine:37 endLine:38}]
[98](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:98)
        pinned_dependencies_test.go:639: test failed: log message not present: [{snippet:/tmp/file3 startLine:28 endLine:28} {snippet:/tmp/file1 startLine:30 endLine:30} {snippet:bash /tmp/file3 startLine:32 endLine:34} {snippet:bash /tmp/file1 startLine:37 endLine:38}]
[99](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:99)
        pinned_dependencies_test.go:639: test failed: log message not present: [{snippet:/tmp/file3 startLine:28 endLine:28} {snippet:/tmp/file1 startLine:30 endLine:30} {snippet:bash /tmp/file3 startLine:32 endLine:34} {snippet:bash /tmp/file1 startLine:37 endLine:38}]
[100](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:100)
        pinned_dependencies_test.go:639: test failed: log message not present: [{snippet:/tmp/file3 startLine:28 endLine:28} {snippet:/tmp/file1 startLine:30 endLine:30} {snippet:bash /tmp/file3 startLine:32 endLine:34} {snippet:bash /tmp/file1 startLine:37 endLine:38}]
[101](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:101)
2022/03/11 15:37:45 curl | sh:   utests.TestReturn{
[102](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:102)
  	Error:         nil,
[103](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:103)
- 	Score:         0,
[104](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:104)
+ 	Score:         10,
[105](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:105)
- 	NumberOfWarn:  4,
[106](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:106)
+ 	NumberOfWarn:  0,
[107](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:107)
- 	NumberOfInfo:  0,
[108](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:108)
+ 	NumberOfInfo:  1,
[109](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:109)
  	NumberOfDebug: 0,
[110](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:110)
  }
[111](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:111)

[112](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:112)
2022/03/11 15:37:45 aws file:   utests.TestReturn{
[113](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:113)
  	Error:         nil,
[114](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:114)
- 	Score:         0,
[115](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:115)
+ 	Score:         10,
[116](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:116)
- 	NumberOfWarn:  15,
[117](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:117)
+ 	NumberOfWarn:  0,
[118](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:118)
- 	NumberOfInfo:  0,
[119](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:119)
+ 	NumberOfInfo:  1,
[120](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:120)
  	NumberOfDebug: 0,
[121](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:121)
  }
[122](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:122)

[123](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:123)
2022/03/11 15:37:45 pkg managers:   utests.TestReturn{
[124](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:124)
  	Error:         nil,
[125](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:125)
- 	Score:         0,
[126](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:126)
+ 	Score:         10,
[127](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:127)
- 	NumberOfWarn:  37,
[128](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:128)
+ 	NumberOfWarn:  0,
[129](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:129)
- 	NumberOfInfo:  0,
[130](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:130)
+ 	NumberOfInfo:  1,
[131](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:131)
  	NumberOfDebug: 0,
[132](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:132)
  }
[133](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:133)

[134](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:134)
2022/03/11 15:37:45 gsutil file:   utests.TestReturn{
[135](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:135)
  	Error:         nil,
[136](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:136)
- 	Score:         0,
[137](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:137)
+ 	Score:         10,
[138](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:138)
- 	NumberOfWarn:  17,
[139](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:139)
+ 	NumberOfWarn:  0,
[140](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:140)
- 	NumberOfInfo:  0,
[141](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:141)
+ 	NumberOfInfo:  1,
[142](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:142)
  	NumberOfDebug: 0,
[143](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:143)
  }
[144](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:144)

[145](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:145)
2022/03/11 15:37:45 wget file:   utests.TestReturn{
[146](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:146)
  	Error:         nil,
[147](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:147)
- 	Score:         0,
[148](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:148)
+ 	Score:         10,
[149](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:149)
- 	NumberOfWarn:  10,
[150](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:150)
+ 	NumberOfWarn:  0,
[151](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:151)
- 	NumberOfInfo:  0,
[152](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:152)
+ 	NumberOfInfo:  1,
[153](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:153)
  	NumberOfDebug: 0,
[154](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:154)
  }
[155](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:155)

[156](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:156)
2022/03/11 15:37:45 proc substitution:   utests.TestReturn{
[157](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:157)
  	Error:         nil,
[158](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:158)
- 	Score:         0,
[159](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:159)
+ 	Score:         10,
[160](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:160)
- 	NumberOfWarn:  6,
[161](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:161)
+ 	NumberOfWarn:  0,
[162](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:162)
- 	NumberOfInfo:  0,
[163](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:163)
+ 	NumberOfInfo:  1,
[164](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:164)
  	NumberOfDebug: 0,
[165](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:165)
  }
[166](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:166)

[167](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:167)
2022/03/11 15:37:45 download with some python:   utests.TestReturn{
[168](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:168)
  	Error:         nil,
[169](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:169)
- 	Score:         0,
[170](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:170)
+ 	Score:         10,
[171](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:171)
- 	NumberOfWarn:  1,
[172](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:172)
+ 	NumberOfWarn:  0,
[173](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:173)
- 	NumberOfInfo:  0,
[174](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:174)
+ 	NumberOfInfo:  1,
[175](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:175)
  	NumberOfDebug: 0,
[176](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:176)
  }
[177](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:177)

[178](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:178)
2022/03/11 15:37:45 wget | /bin/sh:   utests.TestReturn{
[179](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:179)
  	Error:         nil,
[180](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:180)
- 	Score:         0,
[181](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:181)
+ 	Score:         10,
[182](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:182)
- 	NumberOfWarn:  3,
[183](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:183)
+ 	NumberOfWarn:  0,
[184](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:184)
- 	NumberOfInfo:  0,
[185](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:185)
+ 	NumberOfInfo:  1,
[186](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:186)
  	NumberOfDebug: 0,
[187](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:187)
  }
[188](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:188)

[189](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:189)
2022/03/11 15:37:45 curl file sh:   utests.TestReturn{
[190](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:190)
  	Error:         nil,
[191](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:191)
- 	Score:         0,
[192](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:192)
+ 	Score:         10,
[193](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:193)
- 	NumberOfWarn:  12,
[194](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:194)
+ 	NumberOfWarn:  0,
[195](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:195)
- 	NumberOfInfo:  0,
[196](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:196)
+ 	NumberOfInfo:  1,
[197](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:197)
  	NumberOfDebug: 0,
[198](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:198)
  }
[199](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:199)

[200](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:200)
--- FAIL: TestDockerfileScriptDownload (0.00s)
[201](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:201)
    --- FAIL: TestDockerfileScriptDownload/curl_|_sh (0.01s)
[202](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:202)
    --- FAIL: TestDockerfileScriptDownload/aws_file (0.01s)
[203](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:203)
    --- FAIL: TestDockerfileScriptDownload/pkg_managers (0.02s)
[204](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:204)
    --- FAIL: TestDockerfileScriptDownload/gsutil_file (0.01s)
[205](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:205)
    --- FAIL: TestDockerfileScriptDownload/wget_file (0.01s)
[206](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:206)
    --- FAIL: TestDockerfileScriptDownload/proc_substitution (0.01s)
[207](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:207)
    --- FAIL: TestDockerfileScriptDownload/download_with_some_python (0.01s)
[208](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:208)
    --- FAIL: TestDockerfileScriptDownload/wget_|_/bin/sh (0.00s)
[209](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:209)
    --- FAIL: TestDockerfileScriptDownload/curl_file_sh (0.01s)
[210](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:210)
--- FAIL: TestDockerfilePinningFromLineNumber (0.00s)
[211](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:211)
    --- FAIL: TestDockerfilePinningFromLineNumber/Non-pinned_dockerfile (0.00s)
[212](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:212)
        pinned_dependencies_test.go:475: test failed: log message not present: [{snippet:FROM python:3.7 startLine:17 endLine:17}]
[213](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:213)
    --- FAIL: TestDockerfilePinningFromLineNumber/Non-pinned_dockerfile_as (0.00s)
[214](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:214)
        pinned_dependencies_test.go:475: test failed: log message not present: [{snippet:FROM python:3.7 as build startLine:17 endLine:17} {snippet:FROM build startLine:23 endLine:23}]
[215](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:215)
        pinned_dependencies_test.go:475: test failed: log message not present: [{snippet:FROM python:3.7 as build startLine:17 endLine:17} {snippet:FROM build startLine:23 endLine:23}]
[216](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:216)
FAIL
[217](https://github.com/ossf/scorecard/runs/5513098935?check_suite_focus=true#step:5:217)
coverage: 78.8% of statements
```

### PR DESCRIPTION
**Pull request by r0mdau**
#### What kind of change does this PR introduce?

It is a package update.

- [x] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the new behavior (if this is a feature change)?**

- [x] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes

Fixes #1725

#### Special notes for your reviewer

I am not fully aware if the `from` lowercase is really wanted and if my change has some impact in this file `checks/testdata/Dockerfile-pinned-as-without-hash`.

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

```release-note
NONE
```

### CODE REVIEW

File: checks/pinned_dependencies.go [hunk 1]
```diff
@@ -343,7 +343,7 @@ var validateDockerfileIsFreeOfInsecureDownloads fileparser.DoWhileTrueOnFileCont
 		cmdType := child.Value
 
 		// Only look for the 'RUN' command.
-		if cmdType != "run" {
+		if cmdType != "RUN" {
```
Comment (naveensrinivasan) [inline checks/pinned_dependencies.go:346]: Is there a specific reason for this change?

File: checks/pinned_dependencies.go [hunk 2]
```diff
@@ -437,7 +437,7 @@ var validateDockerfileIsPinned fileparser.DoWhileTrueOnFileContent = func(
 
 	for _, child := range res.AST.Children {
 		cmdType := child.Value
-		if cmdType != "from" {
+		if cmdType != "FROM" {
```
Comment (naveensrinivasan) [inline checks/pinned_dependencies.go:440]: Was this the reason the upgrades were failing?

**Review by naveensrinivasan — COMMENTED** [review]
Thank you!

**Review by laurentsimon — APPROVED** [review]

**Review by naveensrinivasan — APPROVED** [review]
